### ISSUE TITLE
Cannot delete Database resource that fails on creation

### ISSUE THREAD

**Issue by joaocc** [aiven/aiven-operator#190]
Hi
We tried creating a Database resource with a name that didn't match some criteria.
We are running operator v0.2.0 on k8s 1.22.
When we try to remove the resource, it doesn't seem to get deleted.

```
403: {"errors":[{"message":"Service database 'aiven-pg-test-220421a' cannot be deleted, reserved name pattern","status":403}],"message":"Service database 'aiven-pg-test-220421a' cannot be deleted, reserved name pattern"} -
```

So it seems that the same error that prevents creation does also prevent deletion.
Any idea on how to remove the resource?
Thanks

**Comment by byashimov** [comment]
Hey. It seems like it's been fixed on the backend. Not a case anymore.
