### ISSUE TITLE
[Kafka] SASL Support

### ISSUE THREAD

**Issue by Dariusch** [aiven/aiven-operator#425]
Hello,

currently., we are using SASL Authentication with Apache Kafka.
According to [your documentation](https://docs.aiven.io/docs/products/kafka/howto/kafka-sasl-auth) and the console, SASL and certificate auth use different ports.

I cannot find any reference in the operator to the SASL port.
Am I just missing it or is it not implemented/exposed yet?

Kind regards
Dariusch

**Comment by byashimov** [comment]
Hi!
Which version of the operator do you use? It's [there](https://aiven.github.io/aiven-operator/api-reference/kafka.html#spec.userConfig.kafka_authentication_methods) :)

**Comment by Dariusch** [comment]
Yes, you can enable it but this is not enough.

Aiven provides a second port, which is different from the port of the Client Certificate, this second port is not exposed via the operator.

**Comment by byashimov** [comment]
Hey @Dariusch 
Please try the latest version. I have released it few moments ago :)
