### ISSUE TITLE
Allow changing the connInfoSecretTarget.name field

### ISSUE THREAD

**Issue by jonatasbaldin** [aiven/aiven-operator#48]
The immutability of the `connInfoSecretTarget.name` field can be an issue. If I mistype the name of the Secret target and I realized that after start using the database I'd need to drop the whole database just to be able to rename the Secret.

As an User, I'd expect a workflow like this:

1. Service is created
2. Secret is created
3. `connInfoSecretTarget.name` is changed
5. Create a new Secret with the new name
6. Remove the old Secret with the old name

We can accomplish this by having a `connInfoSecretTargetName` field in the `.Status` section to keep track of the current Secret name. If there's a change on `.Spec.connInfoSecretTarget.name`, we can create a new Secret and remove the old one.

What do you think?

**Comment by byashimov** [comment]
Hey. 
You can change the name (now?). No need to drop the database.
But:

1. operator won't remove the old secret. If that's just an accident, it can be deleted manually
2. some resources, like "ClickhouseUser" reset password when secret created. So if secret is removed automatically you will loose the creds. That's another reason to do that manually.

Overall this seems to be a dangerous operation to code option 5 on the list.
