### ISSUE TITLE
A way to disable creation of connInfoSecret

### ISSUE THREAD

**Issue by mortenlj** [aiven/aiven-operator#541]
We do our own Just-In-Time provisioning of serviceusers and credentials for our Aiven services, so we don't need or use the secret created by the Aiven Operator (the "connInfoSecret").

Every now and then, some enterprising developer notices that there exists a secret with the same name as the service instance and attempts to use the credentials stored in the connInfoSecret. We would rather that they didn't, and it would be useful if we could just disable the generation of the connInfoSecret entirely.

This is somewhat related to #472 , but while that suggests the operator should use an already existing secret, we want there to be no secret at all.

**Comment by byashimov** [comment]
Hey, thanks for the idea.
I'm taking this to the sprint.
