### ISSUE TITLE
connectionpool.connInfoSecretTarget does not expose CONNECTIONPOOL_NAME

### ISSUE THREAD

**Issue by toredash** [aiven/aiven-operator#560]
It is not possible to get the name of the connectionpool from connInfoSecretTarget. The exposed vars in the secrets are:
```
DATABASE_URI
PGDATABASE
PGHOST
PGPASSWORD
PGPORT
PGSSLMODE
PGUSER
```

`DATABASE_URI` does include the connection pool name, but the value as a whole is not easy to consume for an application via ENVs in our environment.

Is it possible to add the name of the connection pool to the resulting secret ?

**Comment by toredash** [comment]
I looked at the code, but it wasn't clear to me how this secret is populated with values.[Attempt is in the branch](https://github.com/aiven/aiven-operator/compare/main...toredash:aiven-operator:fix/pool-name?expand=1)

**Comment by byashimov** [comment]
Hey @toredash 
Thanks for the report. Let me take a look at this. I'll be right back with a fix.

**Comment by byashimov** [comment]
Connection pool name is actually the CR name. We just need to expose it. [connectionpool_controller.go](https://github.com/aiven/aiven-operator/blob/52b43a7b6d2938bb61cfc71d68b46ac9e1deb31d/controllers/connectionpool_controller.go#L59-L59)

**Comment by toredash** [comment]
@byashimov Could I ask if it is possible to correct the PGPORT that is exposed as well ? The `DATABASE_URI` uses the correct one `26587`, but the `PGPORT` entry is `26586`.

Example:
```
DATABASE_URI: postgres://:26587/connection-pool?sslmode=require
PGPORT: "26586"
```

**Comment by toredash** [comment]
@byashimov thanks! Similar issues are present in https://github.com/aiven/aiven-operator/issues/562. Thanks for quick turnaround
