### ISSUE TITLE
How do I set up externally scraped prometheus endpoints for my PostgresSQL instance?

### ISSUE THREAD

**Issue by danielloader** [aiven/aiven-operator#612]
Hello all, I've started using this operator and so far it's going really well! Database comes up quickly and the secrets are working in apps. Great.

I see you can add an integration for this in the Web UI but not sure how to do it with this operator. Could you please advise?

Thanks

![Screenshot 2024-01-30 at 20-30-51 Service integrations Aiven](https://github.com/aiven/aiven-operator/assets/933423/1c6e94f1-32fd-4cd8-986c-b56e95e66685)

**Comment by Serpentiel** [comment]
Hey, @danielloader! 👋

This should now be available!
