### ISSUE TITLE
Add support for kafka schema registry ACL

### ISSUE THREAD

**Issue by christoffer-eide** [aiven/aiven-operator#617]
Hi. Would it be possible to add support for kafka schema registry ACL in the operator?
https://api.aiven.io/doc/#tag/Service:_Kafka/operation/ServiceSchemaRegistryAclAdd

**Comment by byashimov** [comment]
Hey! Thanks for the request. Added to the backlog.

**Comment by Serpentiel** [comment]
Hey, @christoffer-eide! 👋

It is now implemented and will be released soon.
