### ISSUE TITLE
Errors after upgrading to v0.18.1

### ISSUE THREAD

**Issue by christoffer-eide** [aiven/aiven-operator#709]
We upgraded to v0.18.1. After the new release was rolled out, we started seeing errors in the log:
```
ERROR Reconciler error {
  "controller": "kafkaacl", 
  "controllerGroup": "aiven.io", 
  "controllerKind": "KafkaACL", 
  "KafkaACL": {
    "name":"kafka-producer-acl",
    "namespace":"test-ns"
  }, 
  "namespace": "test-ns", 
  "name": "kafka-producer-acl", 
  "reconcileID": "375dcb78-9868-4779-b824-42cda3cddb94", 
  "error": "kafkaacls.aiven.io \"kafka-producer-acl\" is forbidden: User \"system:serviceaccount:aiven-operator-system:default\" cannot update resource \"kafkaacls/status\" in API group \"aiven.io\" in the namespace \"test-ns\""
}

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler	sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:329sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem	sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:274sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2	sigs.k8s.io/controller-runtime@v0.14.7/pkg/internal/controller/controller.go:235
```
The cluster role [`aiven-operator-role`](https://github.com/aiven/aiven-operator/blob/v0.18.1/charts/aiven-operator/templates/cluster_role.yaml#L241-L250) is missing the `update` verb for the `kafkaacls/status` resource. We added this to the role, and the errors dropped to zero:

![Screenshot 2024-04-10 at 13 24 35](https://github.com/aiven/aiven-operator/assets/114994067/efd1594a-e3e4-42d5-a92e-39420119c577)

**Comment by byashimov** [comment]
Hey @christoffer-eide! Thanks for sharing this.
Could you please share a bit more details on that:
- what version you have upgraded from?
- do you run openshift?

Thanks!

**Comment by Serpentiel** [comment]
Hey, @christoffer-eide! 👋

We've rolled out a fix for the problem. Please expect to see a new release soon.
