### ISSUE TITLE
feat(kafkaschema): add schemaType to allow more then AVRO

### ISSUE THREAD

**Issue by 6uellerBpanda** [aiven/aiven-operator#800]
hi

atm only AVRO schemas can be managed via the operator. 

Would be great if we could also manage JSON and protobuf schemas, maybe via a `schemaType` (suggestion, same as go api client)

**Comment by byashimov** [comment]
Hey! It is already in progress! :) https://github.com/aiven/aiven-operator/pull/797/files#diff-97c39c534db05fef4bc083b3016e1985b1ce9ad0d99a427d6e755616becaafd5R98
